name: Release
on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [master, main]
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # (latest, untagged)
      - name: Version file changed
        id: version-file-changed
        uses: tj-actions/changed-files@76c4d81a6acd339b55bd7407a016981c853eb702 # (latest, untagged)
        with:
          files: lib/blueprinter/version.rb
      - name: Release New Gem Version
        if: ${{ steps.version-file-changed.outputs.any_changed == 'true' }}
        uses: cadwallion/publish-rubygems-action@94a6f4cd5350581749c569b5001eecc864e3ad0b # (latest, untagged)
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBY_GEMS_API_KEY}}
          RELEASE_COMMAND: bundle exec rake release || true # Don't fail when deploy does not take place
