name: Test
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # (latest, untagged)
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Installing dependencies
        run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - name: Run tests
        run: bundle exec rake
      - name: Benchmarks
        run: bundle exec rake benchmarks
