name: Test
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # (latest, untagged)
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Installing dependencies
        run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - name: Run tests
        run: bundle exec rake
      - name: Benchmarks
        run: bundle exec rake benchmarks
